### ISSUE TITLE
Home Page: Add layout for a Carousel of all Capris

### ISSUE THREAD

**Issue by ryanbeiden** [nss-evening-cohort-12/pants-capris#1]
# User Story
As a User on the Home Page, I will see a Carousel of Capris.

# AC
WHEN the User is on the Home Page
THEN they see a Capri section
AND it displays the name of the current Capri
AND an image of the current Capri
AND a button to view to that specific Capri to buy
AND buttons to view the next Capri on that same page

# Dev Notes
**Area on the Home Page to display Capri Carousel:**

<img width="880" alt="Screen Shot 2020-05-07 at 8 16 20 PM" src="https://user-images.githubusercontent.com/25331401/81359774-b212d580-909f-11ea-968b-efa255e01838.png">

* Add a header (```H1 or H2```) for "See Our Capris".
* Put all content under "See Our Capris" in a ```<div></div>``` using Flexbox with ```justify-content: center;```
* Use an Image of the Capri they are viewing.
* With the Image, add a hover changing the opacity to display it is a clickable link.
* Create a Box-Shadow for the Capri Image:
  * Opacity: 75%
  * Color: #444444
  * Size: 8px
* Use a Bootstrap button that will take the user to that specific Capri to buy:
  * ```<a class="btn btn-primary" href="#" role="button">Link</a>```
  * This button's ```href``` will be a  redirect link to the Capris' buy page.
* All buttons and image links should take the User to the same Capri page.
* Add arrows that will eventually become clickable to display the next Capri.
  * Use an image for the arrows that reflects the wireframe.
  * Optional: add box-shadow to arrows.
* Add a description of the Capri under the button, and align it center.

**Fonts & Colors Used:**

```@import url('https://fonts.googleapis.com/css?family=Lemon&display=swap');```
```font-family: 'Lemon', cursive;```
Button & Arrows: ```#c3a61e```
Button Border: ```#927c17```
Text: ```#2a4a4a```

**Comment by RyanBeiden** [comment]
# User Story

# AC
WHEN 
THEN 
AND 

# Dev Notes

**Comment by ryanbeiden** [comment]
I made a few changes as this was being built, and actually implemented issue #11 to this PR since it was the most efficient way. 

- I did not put the ```img``` tag in a div.
- I did not add a ```box-shadow``` to the image, or an ```<a>``` tag to the image either, but instead put a thin border around the carousel and added long ```previous``` and ```next``` buttons.
- I used a Bootstrap Carousel
