### ISSUE TITLE
Luke TODOS

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/pants-capris#19]
- [x] 1. What pages are you making? (literal html pages you need to `touch` or whatever
- [x] 2. #7 need AC, fix up data
- [x] 3. add [bootstrap JS](https://getbootstrap.com/docs/4.0/getting-started/introduction/#js)?
- [x] 4. don't use `window.alert()` or `alert()`, use something from bootstrap/roll your own

**Comment by olamide87** [comment]
updated and fixed issue #7

**Comment by atphy** [comment]
Changed all references to alert windows to instead reference modals, closed to-do 4

**Comment by ryanbeiden** [comment]
Added Bootstrap Carousel link to issue #11

**Comment by ryanbeiden** [comment]
Added an issue showing the HTML files to be used for each page and the universal JS and CSS files on issue #20
