### ISSUE TITLE
History of Capris: Create history Carousel 

### ISSUE THREAD

**Issue by olamide87** [nss-evening-cohort-12/pants-capris#2]

**Comment by olamide87** [comment]
## User Story
As a user, I should 

## AC
WHEN 

THEN 

## Dev Notes

**Comment by olamide87** [comment]
## User Story
As a user, I should see a photo carousel with picture slides that represent the history of capri pants broken down by time period with a short history description 

## AC
WHEN a user clicks on the arrow of the slide show it will go to the next slide it will show the time period, the description of the time period. 

 

## Dev Notes
Write Function named const caruselBuilder to build Domstring to print carousel, reference #7 issue for dataHistory.


Use bootstrap carousel template to create carousel  

```<div class="carousel-item">
  <img src="..." alt="...">
  <div class="carousel-caption d-none d-md-block">
    <h5>...</h5>
    <p>...</p>
  </div>
</div>```

**Comment by olamide87** [comment]
![image](https://user-images.githubusercontent.com/59629698/81349436-98649480-9085-11ea-8e00-e2fb089e8688.png)

**Comment by luketlancaster** [comment]
in the dev notes, show an example of the data you'll use to build the carousel

**Comment by olamide87** [comment]
Updated dev notes included reference to historyData ticket.
