### ISSUE TITLE
Sitewide: Create Buy Capris Page

### ISSUE THREAD

**Issue by atphy** [nss-evening-cohort-12/pants-capris#3]
# User Story
As a user, when I click on a set of capris on the main page carousel, I should be directed to the "Buy Capris" page for that pair of pants..

# AC 
WHEN the user clicks on a pair of pants displayed on the main page carousel
THEN a page loads in the same window displaying information about that pair of pants
AND a user is shown an image of the pants
AND name, price, description, and a current rating are shown
AND the user can select their desired size
AND the user can then add the pants to their cart

# Dev Notes
TO-DO:
- Decide how to display customer cart -- generate a bar at the bottom of the page with some basic info?
- Once we're ready to start work on displaying a "reviews modal," a bold outline should appear around the review stars indicating that they are clickable. On review star click a "reviews modal" will appear displaying customer reviews including first name, state, rating, and review
AND on review star click a modal will appear displaying customer reviews including first name, state, rating, and review

**Comment by atphy** [comment]
![buypage](https://user-images.githubusercontent.com/39771100/81199361-2d816380-8f88-11ea-93b3-a32bd19f091e.PNG)
![buypage modal](https://user-images.githubusercontent.com/39771100/81199389-35410800-8f88-11ea-95d2-6da53d266d6b.PNG)

**Comment by luketlancaster** [comment]
edit the story to use the template provided, with the user story, ac, and dev notes pls

I'd break this up into at least a couple of cards: creating the page, and the modal/review part. Those are decent enough chunks of work to separate

**Comment by atphy** [comment]
Updated the format and bumped everything about the review modal (minus a quick reference in the dev notes) back to a to-do card. Looks better?

**Comment by atphy** [comment]
![buypage2](https://user-images.githubusercontent.com/39771100/81362569-c5756f00-90a6-11ea-9704-aa88903af2aa.PNG)
![buypage modal2](https://user-images.githubusercontent.com/39771100/81362565-c5756f00-90a6-11ea-9d6b-239709bef15f.PNG)
