### ISSUE TITLE
Sitewide: Create and Approve a Style Guide

### ISSUE THREAD

**Issue by atphy** [nss-evening-cohort-12/pants-capris#5]
# Color Guide
- Dark Orange: ```#e5562b```
- Light Orange: ```#f9931e```
- Dirty Yellow: ```#c3a61e```
- Purple: ```#a775d2```
- Red: ```#c31e1e```

- Text, borders, etc: ```#292929```

# Fonts
- Logo Fonts:
-- Capri: Ultra (https://fonts.google.com/specimen/Ultra)
-- & Sons: Lemon (https://fonts.google.com/specimen/Lemon)
- Header Fonts: Lemon (https://fonts.google.com/specimen/Lemon)
- Paragraph Fonts: (tbd -- stick with default Helvetica or try Google's suggested fonts pairs for Lemon)

# Other Design Notes
- Rounded Corners and soft edges
- General "upbeat" 60s vibe to reflect height of popularity for capris during that time period
- Bright colors and soft edges drawn from 60s inspiration, but with a clean modern minimalism
- Tabs are meant to emulate tabs in a planner, so shape and navbar color change should be consistent with that

**Comment by atphy** [comment]
![LogoProspect1](https://user-images.githubusercontent.com/39771100/81202214-e5fcd680-8f8b-11ea-8768-291824331ccc.png)

**Comment by ryanbeiden** [comment]
If it helps, I was using this green color for all nav text and my home page text colors:

```#2a4a4a```
